### PR TITLE
Post.svg image on "submit post" button

### PR DESCRIPTION
**Pull request by danimesq**

### CODE REVIEW

**Comment by Plasmmer** [comment]
@mkg20001

**Review by mkg20001 — CHANGES_REQUESTED** [review]
The change should be done in css/Button.css , because zeronet would overwrite the changes ( css/all.css is auto-generated )

**Comment by danimesq** [comment]
@mkg20001, done.

**Review by mkg20001 — APPROVED** [review]

**Comment by mkg20001** [comment]
@Plasmmer I will publish it tomorrow. Update: Live

**Pull request merged**
