### PR TITLE
New default avatar (200px to fit a future update)

### PR DESCRIPTION
**Pull request by danimesq**

### CODE REVIEW

**Comment by Plasmmer** [comment]
@mkg20001

**Comment by danimesq** [comment]
@mkg20001 this default avatar only appears in the post editor. The default profile avatars are color gradients. I'll implement it and do improvements.

**Comment by mkg20001** [comment]
@Plasmmer Or we just make it similar to twitter by having the gradient in the background and the white user icon in the foreground

**Comment by danimesq** [comment]
@mkg20001 this is what I'm planning. But I can't do it without javascript (I'm not good at JS). I need a code to detect if the avatar has not been uploaded yet that applies a element with a class near the avatar. Then I can add the CSS and foreground I've created:
http://i.imgur.com/Uf4QdJl.png

**Pull request merged**
